doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            username_vo: App\Cart\Infrastructure\ORM\Type\UsernameType
            cantidad_vo: App\Cart\Infrastructure\ORM\Type\CantidadType
            product_id_vo: App\Cart\Infrastructure\ORM\Type\ProductIdType
            orden_id_vo: App\Cart\Infrastructure\ORM\Type\OrdenIdType
            product_name_vo: App\Cart\Infrastructure\ORM\Type\ProductNameType
            product_price_vo: App\Cart\Infrastructure\ORM\Type\ProductPriceType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            CartDomainModel:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Cart/Domain/Model'
                prefix: 'App\Cart\Domain\Model'
                alias: CartDomainModel
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
