# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # Handlers for Commands
    App\Cart\Application\Handler\CreateOrdenHandler:
        tags: [{ name: 'messenger.message_handler' }]

    App\Cart\Application\Handler\CreateOrdenItemHandler:
        tags: [{ name: 'messenger.message_handler' }]

    App\Cart\Application\Handler\UpdateOrdenItemHandler:
        tags: [{ name: 'messenger.message_handler' }]

    App\Cart\Application\Handler\DeleteOrdenItemHandler:
        tags: [{ name: 'messenger.message_handler' }]

    App\Cart\Application\Handler\SetOrdenAsPagadaHandler:
        tags: [{ name: 'messenger.message_handler' }]

    # Handlers for Queries
    App\Cart\Application\Handler\GetOrdenByIdHandler:
        tags: [{ name: 'messenger.message_handler' }]

    App\Cart\Application\Handler\GetOrdenItemByOrdenIdHandler:
        tags: [{ name: 'messenger.message_handler' }]

    App\Cart\Application\Handler\GetProductByIdHandler:
        tags: [{ name: 'messenger.message_handler' }]

        


